AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: EventBridge template

Globals:
  Function:
    Timeout: 5
    CodeUri: src/
    Runtime: python3.12

Parameters:
  EndpointSourceName:
    Type: String
    Default: "EndpointFunction"

Resources:
  MyBus:
    Type: AWS::Events::EventBus

    Properties:
      Name: MyBus

  EndpointFunction:
    Type: AWS::Serverless::Function

    Properties:
      Handler: endpoint.lambda_handler
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref MyBus

      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref MyBus
          EVENT_SOURCE_NAME: !Ref EndpointSourceName

      Events:
        API:
          Type: HttpApi

          Properties:
            Path: /
            Method: POST

  TranslateFunction:
    Type: AWS::Serverless::Function

    Properties:
      Handler: translate.lambda_handler
      Policies:
        - ComprehendBasicAccessPolicy: {}
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "translate:TranslateText"
              Resource: "*"

      Events:
        TranslateFilter:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref MyBus
            Pattern:
              source:
                - !Ref EndpointSourceName
              detail-type:
                - "translate"

  SentimentFunction:
    Type: AWS::Serverless::Function

    Properties:
      Handler: sentiment.lambda_handler
      Policies:
        - ComprehendBasicAccessPolicy: {}

      Events:
        SentimentFilter:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref MyBus
            Pattern:
              source:
                - !Ref EndpointSourceName
              detail-type:
                - "sentiment"

Outputs:
  APIUrl:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
